pixel_size_m: 1000
tile_size_px: 2048
overlap_px: 64
zones:
  "32610": {name: "UTM10N", bbox4326: [-125, 31, -117, 49]}
  "32611": {name: "UTM11N", bbox4326: [-117, 31, -111, 49]}
  "32612": {name: "UTM12N", bbox4326: [-111, 31, -105, 49]}
  "32613": {name: "UTM13N", bbox4326: [-105, 31,  -99, 49]}
  "32614": {name: "UTM14N", bbox4326: [ -99, 25,  -93, 49]}
  "32615": {name: "UTM15N", bbox4326: [ -93, 25,  -87, 49]}
  "32616": {name: "UTM16N", bbox4326: [ -87, 25,  -81, 49]}
  "32617": {name: "UTM17N", bbox4326: [ -81, 24,  -75, 49]}
  "32618": {name: "UTM18N", bbox4326: [ -75, 24,  -69, 49]}
  "32619": {name: "UTM19N", bbox4326: [ -69, 41,  -64, 48]}
nodata: -9999
